# Generated by Django 4.0.6 on 2022-11-11 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.DateField(blank=True, null=True, verbose_name='Возраст')),
                ('date_of_filling_in', models.DateField(blank=True, null=True, verbose_name='Дата заполнения')),
                ('student', models.BooleanField(blank=True, default=False, null=True)),
                ('university', models.TextField(blank=True, null=True)),
                ('gender_info', models.TextField(blank=True, choices=[('men', 'Мужчина'), ('women', 'Женщина')], default='men', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('other', models.TextField(blank=True, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='survey.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='survey.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Emptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=70, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='survey.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Eat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название пищи, напитка')),
                ('water', models.PositiveIntegerField(blank=True, null=True)),
                ('meal_time', models.DateField(blank=True, null=True, verbose_name='Время приема пищи')),
                ('drink', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='survey.eat')),
                ('survey_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='survey.survey')),
            ],
        ),
    ]
