# Generated by Django 4.1.3 on 2022-11-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_remove_eat_title_alter_survey_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='eat',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Наименование продукта'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(blank=True, choices=[(1, 'Неглубокая тарелка'), (2, 'Суповая тарелка'), (3, '1 шт'), (4, '2 шт'), (5, '3 шт'), (6, '1 порция(300 гр)'), (7, '2 порции(500 гр)'), (8, '3 порции'), (9, 'салат (200 гр)')], max_length=50, null=True, verbose_name='Размер порции'),
        ),
    ]
